# Generated by Django 4.0.2 on 2022-02-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('island', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='category_name',
        ),
    ]
